/* auto-generated by NAPI-RS */
/* eslint-disable */
/** AI 分析配置 */
export interface AiAnalysisConfig {
  /** 模型类型 */
  modelType: AIModelType
  /** 模型路径（本地模型） */
  modelPath?: string
  /** API 端点（远程模型） */
  apiEndpoint?: string
  /** API 密钥 */
  apiKey?: string
  /** 是否使用 GPU */
  useGpu?: boolean
  /** 置信度阈值 */
  confidenceThreshold?: number
  /** 模型名称（用于识别） */
  modelName?: string
  /** 最大输出长度（LLM） */
  maxTokens?: number
  /** 温度参数（LLM） */
  temperature?: number
  /** 系统提示词（LLM） */
  systemPrompt?: string
  /** 用户提示词（LLM） */
  userPrompt?: string
  /** 超时时间（秒） */
  timeout?: number
}

/** AI 模型类型 */
export declare const enum AIModelType {
  TensorFlow = 0,
  TensorFlowLite = 1,
  ONNX = 2,
  LocalLLM = 3,
  RemoteAPI = 4
}

/** 分析图片内容（使用 AI 模型） */
export declare function analyzeImageWithAi(imageData: Array<number>, config: AiAnalysisConfig): ImageAnalysisResult

/** 使用 TensorFlow 模型分析图片 */
export declare function analyzeImageWithTensorflow(imageData: Array<number>, modelPath: string): ImageAnalysisResult

/** 使用 TensorFlow Lite 模型分析图片 */
export declare function analyzeImageWithTensorflowLite(imageData: Array<number>, modelPath: string): ImageAnalysisResult

/** 批量分析图片 */
export declare function batchAnalyzeImagesWithAi(imagesData: Array<Array<number>>, config: AiAnalysisConfig): Array<ImageAnalysisResult>

/** 批量压缩图片为WebP格式 */
export declare function batchCompressToWebp(imagesData: Array<Array<number>>, options?: WebPCompressOptions | undefined | null): Array<WebPCompressResult>

/** 批量转换图片格式 */
export declare function batchConvertImageFormat(imagesData: Array<Array<number>>, options: FormatConversionOptions): Array<FormatConversionResult>

/** 边界框 */
export interface BoundingBox {
  /** X坐标 */
  x: number
  /** Y坐标 */
  y: number
  /** 宽度 */
  width: number
  /** 高度 */
  height: number
}

/** 检查模型是否可用 */
export declare function checkModelAvailability(modelPath: string): boolean

/** 颜色信息 */
export interface ColorInfo {
  /** 颜色名称 */
  name: string
  /** RGB值 */
  rgb: [number, number, number]
  /** 占比 */
  percentage: number
  /** 十六进制值 */
  hex: string
}

/** 压缩图片为WebP格式 */
export declare function compressToWebp(imageData: Array<number>, options?: WebPCompressOptions | undefined | null): WebPCompressResult

/** 转换图片格式 */
export declare function convertImageFormat(imageData: Array<number>, options: FormatConversionOptions): FormatConversionResult

/** 检测到的物体 */
export interface DetectedObject {
  /** 物体名称 */
  name: string
  /** 置信度 (0-1) */
  confidence: number
  /** 边界框 */
  bbox: BoundingBox
  /** 类别 */
  category: string
}

/** 下载 TensorFlow 模型 */
export declare function downloadTensorflowModel(modelName: string, modelUrl: string): string

/** 格式转换选项 */
export interface FormatConversionOptions {
  /** 目标格式 */
  targetFormat: string
  /** 压缩质量 (1-100) */
  quality?: number
  /** 是否保持透明度 */
  preserveTransparency?: boolean
  /** 是否无损转换 */
  lossless?: boolean
  /** 颜色空间 */
  colorSpace?: string
  /** 尺寸调整选项 */
  resize?: ResizeOptions
}

/** 格式转换结果 */
export interface FormatConversionResult {
  /** 转换后的数据 */
  data: Array<number>
  /** 原始大小 */
  originalSize: number
  /** 转换后大小 */
  convertedSize: number
  /** 转换后宽度 */
  width: number
  /** 转换后高度 */
  height: number
  /** 原始宽度 */
  originalWidth: number
  /** 原始高度 */
  originalHeight: number
  /** 转换时间 (毫秒) */
  conversionTime: number
}

/** 获取格式的详细信息 */
export declare function getFormatInfo(formatStr: string): string

/** 获取图片信息 */
export declare function getImageInfo(imageData: Array<number>): string

/** 获取支持的图片格式列表 */
export declare function getSupportedFormats(): Array<string>

/** 获取支持的模型列表 */
export declare function getSupportedModels(): Array<string>

/** 图片分析结果 */
export interface ImageAnalysisResult {
  /** 图片类型/格式 */
  imageType: string
  /** 标签列表 */
  tags: Array<string>
  /** 图片描述 */
  description: string
  /** 置信度 (0-1) */
  confidence: number
  /** 检测到的物体 */
  objects: Array<DetectedObject>
  /** 主要颜色 */
  colors: Array<ColorInfo>
  /** 场景类型 */
  sceneType: string
  /** 分析时间（毫秒） */
  analysisTime: number
  /** 使用的模型 */
  modelUsed: string
}

/** 本地 LLM 配置 */
export interface LocalLlmConfig {
  /** 模型路径 */
  modelPath: string
  /** 模型类型（llama, mistral, etc.） */
  modelType: string
  /** 上下文长度 */
  contextLength?: number
  /** 批处理大小 */
  batchSize?: number
  /** 线程数 */
  threads?: number
}

/** 简单的加法函数，用于测试WASM接口 */
export declare function plus100(input: number): number

/** 远程 API 配置 */
export interface RemoteApiConfig {
  /** API 类型 */
  apiType: RemoteAPIType
  /** API 端点 */
  endpoint: string
  /** API 密钥 */
  apiKey: string
  /** 模型名称 */
  modelName: string
  /** 版本 */
  version?: string
  /** 额外头部信息 */
  headers?: Record<string, string>
}

/** 远程 API 服务类型 */
export declare const enum RemoteAPIType {
  OpenAI = 0,
  Qwen = 1,
  Claude = 2,
  Gemini = 3,
  Custom = 4
}

/** 尺寸调整选项 */
export interface ResizeOptions {
  /** 目标宽度 */
  width?: number
  /** 目标高度 */
  height?: number
  /** 是否保持宽高比 */
  maintainAspectRatio?: boolean
}

/** WebP压缩配置 */
export interface WebPCompressOptions {
  /** 压缩质量 (0-100) */
  quality?: number
  /** 是否使用无损压缩 */
  lossless?: boolean
}

/** WebP压缩结果 */
export interface WebPCompressResult {
  /** 压缩后的数据 */
  data: Array<number>
  /** 原始大小 */
  originalSize: number
  /** 压缩后大小 */
  compressedSize: number
  /** 压缩率 (0-1) */
  compressionRatio: number
  /** 压缩后的宽度 */
  width: number
  /** 压缩后的高度 */
  height: number
}
