/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 批量压缩图片为WebP格式 */
export declare function batchCompressToWebp(imagesData: Array<Array<number>>, options?: WebPCompressOptions | undefined | null): Array<WebPCompressResult>

/** 压缩图片为WebP格式 */
export declare function compressToWebp(imageData: Array<number>, options?: WebPCompressOptions | undefined | null): WebPCompressResult

/** 获取图片信息 */
export declare function getImageInfo(imageData: Array<number>): string

export declare function plus100(input: number): number

/** WebP压缩配置 */
export interface WebPCompressOptions {
  /** 压缩质量 (0-100) */
  quality?: number
  /** 是否使用无损压缩 */
  lossless?: boolean
}

/** WebP压缩结果 */
export interface WebPCompressResult {
  /** 压缩后的数据 */
  data: Array<number>
  /** 原始大小 */
  originalSize: number
  /** 压缩后大小 */
  compressedSize: number
  /** 压缩率 (0-1) */
  compressionRatio: number
  /** 压缩后的宽度 */
  width: number
  /** 压缩后的高度 */
  height: number
}
