// Generated by build:vercel-api from gitee-proxy.entry.ts — do not edit

// ../../packages/plugin-provider-gitee/src/proxy/constants.ts
var GITEE_PROXY_PATH = '/api/gitee-proxy';

// ../../packages/plugin-provider-gitee/src/proxy/giteeImageProxy.ts
var GITEE_REQUEST_HEADERS = {
  Referer: 'https://gitee.com/',
  Origin: 'https://gitee.com',
  'User-Agent': 'Pixuli-Web/1.0',
};
function parseGiteeProxyRequest(requestUrl) {
  const [pathname, search = ''] = requestUrl.split('?');
  const escaped = GITEE_PROXY_PATH.replace(/\//g, '\\/');
  const match = pathname.match(new RegExp(`${escaped}\\/?(.*)$`));
  const giteePath = match?.[1] ? decodeURIComponent(match[1]) : '';
  const params = new URLSearchParams(search);
  params.delete('path');
  const queryString = params.toString();
  return { giteePath, queryString };
}
async function fetchGiteeImage(giteePath, queryString = '', method = 'GET') {
  if (!giteePath) {
    throw new ProxyError(400, 'Invalid path: gitee path is required');
  }
  const giteeUrl = `https://gitee.com/${giteePath}${queryString ? `?${queryString}` : ''}`;
  return fetch(giteeUrl, {
    method,
    redirect: 'follow',
    headers: GITEE_REQUEST_HEADERS,
  });
}
var ProxyError = class extends Error {
  status;
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
function setResponseStatus(res, status) {
  if (typeof res.status === 'function') {
    res.status(status);
  } else {
    res.statusCode = status;
  }
}
function endResponse(res, body) {
  if (typeof res.send === 'function') {
    res.send(body);
  } else {
    res.end(body);
  }
}
function setCorsHeaders(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, HEAD, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', '*');
}
async function handleGiteeImageProxy(req, res) {
  const method = req.method || 'GET';
  if (method !== 'GET' && method !== 'HEAD' && method !== 'OPTIONS') {
    setResponseStatus(res, 405);
    res.setHeader('Content-Type', 'application/json');
    endResponse(res, JSON.stringify({ error: 'Method not allowed' }));
    return;
  }
  if (method === 'OPTIONS') {
    setResponseStatus(res, 200);
    setCorsHeaders(res);
    endResponse(res);
    return;
  }
  try {
    const requestUrl = req.url || '';
    let { giteePath, queryString } = parseGiteeProxyRequest(requestUrl);
    if (!giteePath && req.url) {
      try {
        const host = req.headers.host || 'localhost';
        const parsed = new URL(requestUrl, `http://${host}`);
        const pathParam = parsed.searchParams.get('path');
        if (pathParam) {
          giteePath = pathParam;
          parsed.searchParams.delete('path');
          queryString = parsed.searchParams.toString();
        }
      } catch {}
    }
    const upstream = await fetchGiteeImage(giteePath, queryString, method);
    if (!upstream.ok) {
      setResponseStatus(res, upstream.status);
      res.setHeader('Content-Type', 'application/json');
      endResponse(
        res,
        JSON.stringify({
          error: `Failed to fetch: ${upstream.status} ${upstream.statusText}`,
        }),
      );
      return;
    }
    const contentType =
      upstream.headers.get('content-type') || 'application/octet-stream';
    setResponseStatus(res, 200);
    setCorsHeaders(res);
    res.setHeader('Content-Type', contentType);
    res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
    if (method === 'HEAD') {
      endResponse(res);
      return;
    }
    const buffer = Buffer.from(await upstream.arrayBuffer());
    endResponse(res, buffer);
  } catch (error) {
    const status = error instanceof ProxyError ? error.status : 500;
    setResponseStatus(res, status);
    res.setHeader('Content-Type', 'application/json');
    endResponse(
      res,
      JSON.stringify({
        error: error instanceof Error ? error.message : 'Internal server error',
      }),
    );
  }
}

// api/gitee-proxy.entry.ts
async function handler(req, res) {
  await handleGiteeImageProxy(req, res);
}
export { handler as default };
