/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 批量压缩图片为WebP格式 */
export declare function batchCompressToWebp(imagesData: Array<Array<number>>, options?: WebPCompressOptions | undefined | null): Array<WebPCompressResult>

/** 批量转换图片格式 */
export declare function batchConvertImageFormat(imagesData: Array<Array<number>>, options: FormatConversionOptions): Array<FormatConversionResult>

/** 压缩图片为WebP格式 */
export declare function compressToWebp(imageData: Array<number>, options?: WebPCompressOptions | undefined | null): WebPCompressResult

/** 转换图片格式 */
export declare function convertImageFormat(imageData: Array<number>, options: FormatConversionOptions): FormatConversionResult

/** 格式转换选项 */
export interface FormatConversionOptions {
  /** 目标格式 */
  targetFormat: string
  /** 压缩质量 (1-100) */
  quality?: number
  /** 是否保持透明度 */
  preserveTransparency?: boolean
  /** 是否无损转换 */
  lossless?: boolean
  /** 颜色空间 */
  colorSpace?: string
  /** 尺寸调整选项 */
  resize?: ResizeOptions
}

/** 格式转换结果 */
export interface FormatConversionResult {
  /** 转换后的数据 */
  data: Array<number>
  /** 原始大小 */
  originalSize: number
  /** 转换后大小 */
  convertedSize: number
  /** 转换后宽度 */
  width: number
  /** 转换后高度 */
  height: number
  /** 原始宽度 */
  originalWidth: number
  /** 原始高度 */
  originalHeight: number
  /** 转换时间 (毫秒) */
  conversionTime: number
}

/** 获取格式的详细信息 */
export declare function getFormatInfo(formatStr: string): string

/** 获取图片信息 */
export declare function getImageInfo(imageData: Array<number>): string

/** 获取支持的图片格式列表 */
export declare function getSupportedFormats(): Array<string>

/** 简单的加法函数，用于测试WASM接口 */
export declare function plus100(input: number): number

/** 尺寸调整选项 */
export interface ResizeOptions {
  /** 目标宽度 */
  width?: number
  /** 目标高度 */
  height?: number
  /** 是否保持宽高比 */
  maintainAspectRatio?: boolean
}

/** WebP压缩配置 */
export interface WebPCompressOptions {
  /** 压缩质量 (0-100) */
  quality?: number
  /** 是否使用无损压缩 */
  lossless?: boolean
}

/** WebP压缩结果 */
export interface WebPCompressResult {
  /** 压缩后的数据 */
  data: Array<number>
  /** 原始大小 */
  originalSize: number
  /** 压缩后大小 */
  compressedSize: number
  /** 压缩率 (0-1) */
  compressionRatio: number
  /** 压缩后的宽度 */
  width: number
  /** 压缩后的高度 */
  height: number
}
